### ISSUE TITLE
I can hook libc.so can't work

### ISSUE THREAD

**Issue by muyi126** [iqiyi/xHook#10]
,I want hook "open" and close but  "open " can't work,"close" loop  execution

public void copyFile(String oldPath, String newPath) {
        try {
            int bytesum = 0;
            int byteread = 0;
            File oldfile = new File(oldPath);
            if (oldfile.exists()) { 
                InputStream inStream = new FileInputStream(oldPath); 
                FileOutputStream fs = new FileOutputStream(newPath);
                byte[] buffer = new byte[1444];
                int length;
                while ( (byteread = inStream.read(buffer)) != -1) {
                    bytesum += byteread;
                    fs.write(buffer, 0, byteread);

                }
                inStream.close();
            }
        }
        catch (Exception e) {
            e.printStackTrace();

        }

    }

**Comment by caikelun** [comment]
Try this:
```
xhook_register(".*\\.so$", "close", my_close, &origin_close);
```
