### ISSUE TITLE
hook getaddrinfo

### ISSUE THREAD

**Issue by rockstore** [iqiyi/xHook#11]
excuse me , when i use xhook to hook getaddrinfo, i just modify biz.c and add:
xhook_register("^/system/.*\\.so$", "getaddrinfo", my_getaddrinfo, NULL); xhook_register("^/vendor/.*\\.so$", "getaddrinfo", my_getaddrinfo, NULL);

my_getaddrinfo is defined as following:

static int my_getaddrinfo(const char* hostname, const char* servname,
    const struct addrinfo* hints, struct addrinfo** res) {
    LOGD("rock_hook getaddrinfo");
    return getaddrinfo(hostname, servname, hints, res);
}

however , when I load a webview with http://www.google.com, I can not receive the log, can you help me ?

**Comment by caikelun** [comment]
try this:

xhook_register("^/system/.*\\.so$", "getaddrinfo", my_getaddrinfo, NULL); xhook_register("^/vendor/.*\\.so$", "getaddrinfo", my_getaddrinfo, NULL);

**Comment by rockstore** [comment]
excuse me, I use cmake to build hook as a library of my native lib, and forder structure is 
--/xhook
--native-lib.cpp

two CMakeLists.txt files are placed in root folder and xhook, in native-lib.cpp, i use xhook to registe and refresh the __android_log_print. question is  that xhook can take effect sometimes, and sometimes it does not work, can you help me?

**Comment by caikelun** [comment]
You can turn on the xhook debug switch by:

```
xhook_enable_debug(1);
```

Then trace the logcat(tag: "xhook") to see what happend.

**Comment by rockstore** [comment]
excuse me, I try to hook getaddrinfo,  after xhook_refresh executes , log shows that xhook successfully hook "getaddrinfo" with "XH_HK_OK 0x7fb57bfac8: 0x7fb572ccf4 -> 0x7fb198ec78 getaddrinfo /system/lib64/libc.so". My local function is defined as following:
static int my_getaddrinfo(const char* hostname, const char* servname,
                          const struct addrinfo* hints, struct addrinfo** res) {
    LOGD("hook getaddrinfo");
    return getaddrinfo(hostname, servname, hints, res);
}

however ,when i try to connect "www.google.com" using httpurlconnection, "hook getaddrinfo" does not appears, can you help me?

**Comment by caikelun** [comment]
According to my research in Android 8.0.0_r4 source code, HttpURLConnection does **NOT** use getaddrinfo() internal. The calling process of DNS lookup in HttpURLConnection:
* [lookupHostByName](http://androidxref.com/8.0.0_r4/xref/libcore/ojluni/src/main/java/java/net/Inet6AddressImpl.java#122)
* [Linux_android_getaddrinfo](http://androidxref.com/8.0.0_r4/xref/libcore/luni/src/main/native/libcore_io_Linux.cpp#1179)
* [android_getaddrinfofornet](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/getaddrinfo.c#567)
* [android_getaddrinfofornetcontext](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/getaddrinfo.c#581)
* [explore_fqdn](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/getaddrinfo.c#794)
* [nsdispatch](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/nsdispatch.c#100)
* [_dns_getaddrinfo](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/getaddrinfo.c#1889)

[getaddrinfo](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html) is defined in POSIX, and implemented in both GNU libc and Android bionic ( ref: [here](http://androidxref.com/8.0.0_r4/xref/bionic/libc/dns/net/getaddrinfo.c#560)  ).

**Comment by Guolei1130** [comment]
in 8.0
```
xhook_register("/system/lib/libjavacore.so",  "android_getaddrinfofornet", (void *)new_android_getaddrinfofornet,  NULL)
```

**Comment by fr0zenrain** [comment]
It seems android high version (6.0+) had big changes, do resolve in other process ?
