### ISSUE TITLE
Have problems to hook "new" rather than "malloc" in libtest.so

### ISSUE THREAD

**Issue by UhlanZW** [iqiyi/xHook#12]
I have used it to hook "malloc" in libtest.so and it works. However, I can not hook  "new" in libtest.so. Is this possible? 
With the follow code:
xhook_register(".*\\.so$", "malloc",  (void*)my_malloc,  NULL);
  xhook_ignore(".*/libbiz\\.so$", "malloc");
I can hook "new" in libtest.so in this way.
However, if I try to use data structure in standard library to record some memory information(e.g. unordered_map) in biz.cpp, "new" can not be hooked. It seems that any called "new" in biz.cpp can cause that problem, maybe I have used this tool in a wrong way, I wish that anyone can help me, thanks.

**Comment by caikelun** [comment]
"new" is a C++ keyword, not a symbol name(function name). You can try to disassemble your dynamic library, to find the symbol which transformed from "new". Try to google: "c++ new _Znwj". Tips:
```
_Znwj -> new
_Znaj -> new[]
```
Enjoy~

**Comment by UhlanZW** [comment]
Thank you very much for your help, it really works, in fact, following symbols should be hooked.
extern "C" void  _ZdlPv (void*);
extern "C" void* _Znwj (unsigned);
extern "C" void  _ZdaPv (void*);
extern "C" void* _Znaj (unsigned);

**Comment by caikelun** [comment]
🍺

**Comment by JiaoYanMoGu** [comment]
> 

Could you please paste the sample code here, because I'm doing the same thing now, but I couldn't hook the new or delete , Thanks!
