### ISSUE TITLE
如果要hook c++里某个类的方法，怎么写呢

### ISSUE THREAD

**Issue by wuyuhang** [iqiyi/xHook#14]
把要hook的目标.so反编译后，里面的目标函数是一个c++的类的成员方法，但是xhook好像没有提供一个参数是被hook函数的类名

**Comment by caikelun** [comment]
C++ 方法名在编译时会被 mangle 成一个字符串（其中包含了 namespace, class, 参数和返回类型等信息）。可以用 readelf 查看一下你要hook的目标so。请 google: “c++ symbol mangle demangle”。

https://en.wikipedia.org/wiki/Name_mangling
http://demangler.com/
