### ISSUE TITLE
xhook_register 返回1002 怎么处理

### ISSUE THREAD

**Issue by czgczg308** [iqiyi/xHook#21]
xhook_register 时候 返回1002 这个代表的是什么错误

**Comment by czgczg308** [comment]
不过我这个 是参考 你们 demo来写的 不知道 哪里写的不对，能帮忙看一下吗
我就先串改libxhookmethod.so中的这个方法
JNIEXPORT void JNICALL Java_com_yztc_devicetool_nat_JniXhookMethod_log
        (JNIEnv * env, jclass object)
{
    __android_log_print(ANDROID_LOG_VERBOSE,"czg","我是原始的log");
}

--------------------------------------------------------------
static int my_hook_log_print(int prio, const char* tag, const char* fmt, ...)
{
    va_list ap;
    char buf[1024];
    int r;
    snprintf(buf, sizeof(buf), "[%s] %s","来来来底层被串改了", (NULL == fmt ? "" : fmt));

    va_start(ap, fmt);
    r = __android_log_vprint(prio, "czg", buf, ap);
    va_end(ap);
    return r;
}

JNIEXPORT void JNICALL Java_com_yztc_devicetool_nativehook_NativeHandler_doHook
  (JNIEnv * env, jobject j_obj){
    int a= xhook_register("^/system/.*\\.so$",  "__android_log_print", my_hook_log_print,  NULL);
    int b =xhook_register("^/vendor/.*\\.so$",  "__android_log_print", my_hook_log_print,  NULL);
    int c = xhook_register(".*/libxhookmethod\\.so$", "__android_log_print", my_hook_log_print, NULL);

    __android_log_print(ANDROID_LOG_VERBOSE,"czg","我hook初始化了%d,%d,%d",a,b,c);

    //just for testing
    xhook_ignore(".*/liblog\\.so$", "__android_log_print"); //ignore __android_log_print in liblog.so
    xhook_ignore(".*/libjavacore\\.so$", NULL); //ignore all hooks in libjavacore.so
}

**Comment by caikelun** [comment]
只需要hook libxhookmethod.so就可以了，注意下正则的语法：
```
xhook_register(".*/libxhookmethod\\.so$", "__android_log_print", my_hook_log_print, NULL);
xhook_refresh(1);
```

**Comment by czgczg308** [comment]
好的 谢谢你！这锻还是 报1002 ，我去稍微 看看 里面 源码！看看 哪里 还有问题！有问题的话 我在来请教你

**Comment by caikelun** [comment]
好的，不客气。

**Comment by caikelun** [comment]
先改成
```
xhook_refresh(0);
```
试试吧，`0`表示同步执行hook操作，这样refresh返回时hook肯定执行完了。还是不行的话，就打开xhook的调试输出（`xhook_enable_debug(1);`），看下logcat输出。

**Comment by caikelun** [comment]
你可以大致了解下PLT/GOT hook的原理，只能hook动态库之间的调用。hook设备信息/MAC获取这些我没试过，如果能找到合适的hook点，应该是可以实现的。

**Comment by czgczg308** [comment]
好的谢谢
