### ISSUE TITLE
用2中写法 hook mmap方法都会报错

### ISSUE THREAD

**Issue by zhangxy123666** [iqiyi/xHook#23]
环境: Android 6.0  x86模拟器 

void *( my_mmap)(void *start, size_t len, int prot, int flags, int fd, off_t offset){
    LOGD(" [mmap] =========“);
    return  old_mmap11(start, len, prot, flags, fd, offset);
};

xhook_register(".*libc\\.so$", "mmap",   (void *)my_mmap,   NULL);   // 第一种写法
xhook_register("^/system/.*$", "mmap",   my_mmap,   NULL);            // 第二种写法
xhook_refresh(1);

第一种方式

![image](https://user-images.githubusercontent.com/41684879/47059680-fe1bd200-d1fc-11e8-9d7e-758c4b287f8a.png)
看log是执行到了，但是崩溃了，my_mmap执行了，但是崩溃了

第二种方式
![image](https://user-images.githubusercontent.com/41684879/47059582-8b125b80-d1fc-11e8-9921-b906ffca0720.png)
看日志应该是hook有输出  ，但是实际 my_mmap没有执行

**Comment by zhangxy123666** [comment]
syscall，这样调用还是会崩溃，另外我这里只有 SYS_mmap2这个参数
![image](https://user-images.githubusercontent.com/41684879/47060641-fe1dd100-d200-11e8-9c99-1998956c5272.png)

**Comment by caikelun** [comment]
```
void *my_mmap(void *start, size_t len, int prot, int flags, int fd, off_t offset)
{
    LOGD("[mmap] =========");
    return mmap(start, len, prot, flags, fd, offset);
};

xhook_register("^/system/.*$", "mmap", my_mmap, NULL);
```
这样调用会崩溃吗？

**Comment by zhangxy123666** [comment]
这样调用正常了，请教一下，我觉得这样不是会陷入死循环吗，为什么没有呢

**Comment by caikelun** [comment]
因为你的代码只对符合 `^/system/.*$` 正则的 ELF 做了hook，而 `my_mmap` 所在的so库不在 `/system` 目录下，所以没有被hook到。

如果你配置的正则包含了 `my_mmap` 所在的so库，就会陷入死循环。如果要避免死循环，就需要避免对 `mmap` 的直接依赖，改成这样：

```
typedef void (*my_mmap_t)(void *, size_t, int, int, int, off_t);
my_mmap_t old_mmap = NULL;

void *my_mmap(void *start, size_t len, int prot, int flags, int fd, off_t offset)
{
    LOGD("[mmap] =========");
    return old_mmap(start, len, prot, flags, fd, offset);
};

xhook_register("^/.*$", "mmap", my_mmap, (void **)&old_mmap);
```

**Comment by zhangxy123666** [comment]
我的理解是：

hook了 libc.so中的 mmap函数，然后所有调用mmap的时候都执行钩子函数，
你在上面提到的 my_mmap
![image](https://user-images.githubusercontent.com/41684879/47066605-3a5d2b80-d219-11e8-87e8-536c14047cd9.png)

不是很理解这句话，我要Hook的是mmap，我理解为my_mmap替换了mmap

为什么你提到了是我要hook     my_mmap，大佬帮忙解惑下



是不是可以理解为：hook到的只是用正则匹配到的调用mmap的地方

**Comment by caikelun** [comment]
xhook是通过替换PLT/GOT中的函数地址达到hook效果的，不是inline hook的方式。通俗的说：假设mmap的实现在libc.so中，libbiz.so中有逻辑调用了mmap函数，xhook替换的是“libbiz.so运行时指向libc.so中的mmap函数的指针”，并不是替换libc.so中mmap的实现逻辑。

建议看一下这篇文字：https://github.com/iqiyi/xHook/blob/master/docs/overview/android_plt_hook_overview.zh-CN.md

**Comment by zhangxy123666** [comment]
谢谢啦，这个问题搞懂了，给你点个赞  :)

**Comment by caikelun** [comment]
不客气的
