### ISSUE TITLE
发现只能修改单个PAGESIZE的BUG

### ISSUE THREAD

**Issue by zogvm** [iqiyi/xHook#25]
xh_util.c里面

#define PAGE_START(addr) ((addr)&PAGE_MASK)
#define PAGE_END(addr) (PAGE_START(addr + sizeof(uintptr_t) - 1) + PAGE_SIZE)
原来的
#define PAGE_COVER(addr) (PAGE_END(addr) - PAGE_START(addr))
我的修复：
#define PAGE_COVER(saddr,eaddr) (PAGE_END(eaddr) - PAGE_START(saddr))

xh_util_flush_instruction_cache函数和xh_util_set_addr_protect 函数都要改

**Comment by caikelun** [comment]
`mprotect`和`__builtin___clear_cache`仅用于操作某个“函数指针的地址”，需要操作的数据长度仅为一个地址值的长度（uintptr_t），远小于Linux/Android默认的PAGESIZE值（4K）。所以PAGE_COVER会根据addr是否跨越4K边界，来返回4K或8K，仅存在这两种情况，并不需要根据一组起始地址来判断COVER的长度。
