### ISSUE TITLE
just get the old func

### ISSUE THREAD

**Issue by rockstore** [iqiyi/xHook#26]
execuse me, in my case , i just want to get the old_func and invoke it .
those are my logic:
void **old_func = NULL;
but when i try xhook_register(".*/libart\\.so$",  "XXX",  NULL,  old_func), 
old_func is always NULL,  can xhook just get the address of old_func?

**Comment by caikelun** [comment]
No. The third argument of `xhook_register` must be a valid function pointer.
In addition, the function pointer hooked(replaced) by xHook is point to a function in another library, not in the library itself. Pls google “PLG GOT ELF ...”.
In your case, maybe what you need is dlopen/dladdr ?
