### ISSUE TITLE
可以定位泄漏处吗？

### ISSUE THREAD

**Issue by liuxwdz** [iqiyi/xHook#27]
可以定位泄漏处吗？

**Comment by caikelun** [comment]
xHook本身不提供定位内存泄漏的功能，你可以基于 xHook 自己实现此类功能。参考：
1. hook malloc/realloc/free/strdup/......
2. 在 hook 函数中记录backtrace以便在判定泄露时定位。demo或本地测试验证可以通过 `_Unwind_Backtrace` 和 `_Unwind_GetIP` 获取backtrace，但是`_Unwind_xxx` 系列兼容性和执行效率都有些问题，上线的话，还是建议实现自己的优化定制的unwind机制。
