### ISSUE TITLE
xHook使用上的一点疑问

### ISSUE THREAD

**Issue by xiaoyaomeng** [iqiyi/xHook#28]
想请教下，
1.demo里写的biz.c这边，我去除了libtest.so的hook的话，那这样不是应该会hook到系统的__android_log_print函数吗？但是，输出的Log证明并没有生效，是我理解有误吗？

2.definitely failed when compiled with -O0  这个表示什么意思哈，局部定义的函数hook不到吗？

麻烦大神看到给个回复哈，公司做项目要用到，现在卡在这边，感谢！

biz.c
`void Java_com_qiyi_biz_NativeHandler_start(JNIEnv* env, jobject obj)
{
    (void)env;
    (void)obj;

    xhook_register("^/system/.*\\.so$",  "__android_log_print", my_system_log_print,  NULL);
    xhook_register("^/vendor/.*\\.so$",  "__android_log_print", my_system_log_print,  NULL);
    //xhook_register(".*/libtest\\.so$", "__android_log_print", my_libtest_log_print, NULL);

    //just for testing
    //xhook_ignore(".*/liblog\\.so$", "__android_log_print"); //ignore __android_log_print in liblog.so
    //xhook_ignore(".*/libjavacore\\.so$", NULL); //ignore all hooks in libjavacore.so
}`

2019-01-03 15:53:49.137 8594-8618/com.qiyi.xhookwrapper D/mytest: call directly. 216
2019-01-03 15:53:49.137 8594-8618/com.qiyi.xhookwrapper D/mytest: call from global ptr. 216
2019-01-03 15:53:49.137 8594-8618/com.qiyi.xhookwrapper D/mytest: call from local ptr. 216
2019-01-03 15:53:49.137 8594-8618/com.qiyi.xhookwrapper D/mytest: call from local ptr2. 216 (definitely failed when compiled with -O0)

**Comment by caikelun** [comment]
1. 你去掉了对libtest.so的hook，所以logcat中输出的tag依然是mytest，没有被hook（你贴的log中已体现）。。你保留了对系统库的hook，所以当系统库写logcat时，tag应该会被修改为xhook_system（你贴的log中并没有体现出来）。

2. 编译加-O0时，__android_log_print的函数地址被赋值到my_local_log_ptr2变量中，这个赋值操作在libtest.so被调用start时已经完成了，之后，biz中的逻辑才对libtest.so执行hook操作，修改的是PLT中的值，局部变量的值不会尝试去修改，所以对于my_local_log_ptr2的调用依然会调用到原始的函数中。-O1/-O2之类的优化，my_local_log_ptr2会被直接优化掉，优化为直接对__android_log_print的调用，就不会产生这个问题了。具体可以对比下-O0和-O2的反汇编输出。

**Comment by xiaoyaomeng** [comment]
@caikelun 感谢大神的耐心回复，看来我理解错了，您这边框架xhook_register后面指定的so，是对应的hook，我想再请问下，现在这样写是实现了对系统库log输出函数的hook，而假设我们又A.so和B.so里面都用到了系统库的这个log函数的话，那就必须要xhook_register这两个so吗？没有办法像Xposed JAVA层的hook那样子直接hook系统方法后，任何调用方就都会生效那样吗？

**Comment by caikelun** [comment]
是的，需要分别xhook_register你的A.so和B.so。xhook属于PLT/GOT hook类型的框架，主要是为了简单和稳定，但使用场景不如inline hook广泛。

你可以了解下inline hook，比如frida和substrate应该能满足你的需求。

**Comment by xiaoyaomeng** [comment]
@caikelun 好的，谢谢您！inline hook的话，目前了解的好像都不支持x86，这是一个硬伤.
