### ISSUE TITLE
能hook 别人app 中so 中的方法吗？

### ISSUE THREAD

**Issue by ranshon** [iqiyi/xHook#29]
如果可以 路径的正则是从 com.xxx.xxx  开始，还是直接写xxx.so 就可以

**Comment by mumaren** [comment]
只能 hook 本进程内的,只要能注入进去就可以.

**Comment by caikelun** [comment]
xhook 本身包含的逻辑以及暴露的 API，只提供 hook 本进程 ELF 的功能。你可以自己实现一段逻辑，把 xhook 的加载和调用逻辑注入到目标进程里。

**Comment by ranshon** [comment]
我看官方文档说，要hook 其他进行需要root ，我只需要demo里 申请root权限就可以吗

**Comment by caikelun** [comment]
准确的说：如果”执行注入的进程“和”被注入的进程“不在一个进程组中，”执行注入的进程“需要有root权限才能执行注入操作。注入和hook是两件彼此分离的事情，权限只和注入相关，与hook无关。

**Comment by ranshon** [comment]
也就是说 xhook 这个库 只有hook 功能 ， 没有注入功能吧

**Comment by caikelun** [comment]
> 也就是说 xhook 这个库 只有hook 功能 ， 没有注入功能吧

是的
