### ISSUE TITLE
HOOK 失败的BUG

### ISSUE THREAD

**Issue by xqyphp** [iqiyi/xHook#31]
case DT_HASH: 此时应该加个判断 self->is_use_gnu_hash 跳过，或者建立其他的bucket变量，否则会被覆盖，而且按gnu查找的时候会查找不到

**Comment by xqyphp** [comment]
不客气，另外提个意见，能不能加上直接修改导出表的功能，就是直接修改sym的地址，在实际用的时候有个情况是被hook的so加载较早，后面其他so调用这个函数的时机不能确定，现有的貌似不能满足需求，我自己稍微修改了一下使用了，可能不严谨。

**Comment by xqyphp** [comment]
不客气，另外提个意见，能不能加上直接修改导出表的功能，就是直接修改sym的地址，在实际用的时候有个情况是被hook的so加载较早，后面其他so调用这个函数的时机不能确定，现有的貌似不能满足需求，我自己稍微修改了一下使用l了。

**Comment by caikelun** [comment]
嗯嗯，有空我研究一下加上这个功能，导出表hook有些场景下确实也挺有用的。我们目前自己的使用场景相对固定一些，就是在dlopen或System.loadLirary几个特定的so库后，立刻用xhook去hook一些系统调用，做一些性能/泄露/统计分析的事情。

以后多交流哦~ 🍻

**Comment by xqyphp** [comment]
嗯，以后多交流，我是直接修改的symtab的st_value，能实现功能，不知道会不会有其他问题。
