### ISSUE TITLE
这是什么问题呢，全部failed

### ISSUE THREAD

**Issue by netstu** [iqiyi/xHook#36]
02-15 19:45:28.215: E/xhook(9452): get addr prot failed. ret: 1009
02-15 19:45:28.216: E/xhook(9452): replace function failed: fopen at .rel.plt
02-15 19:45:28.269: E/xhook(9452): get addr prot failed. ret: 1009
02-15 19:45:28.269: E/xhook(9452): replace function failed: access at .rel.plt
02-15 19:45:28.287: E/xhook(9452): get addr prot failed. ret: 1009
02-15 19:45:28.287: E/xhook(9452): replace function failed: chdir at .rel.plt
02-15 19:45:28.351: E/xhook(9452): get addr prot failed. ret: 1009
02-15 19:45:28.351: E/xhook(9452): replace function failed: __system_property_get at .rel.plt

**Comment by netstu** [comment]
找到原因了，是hook了libwebviewchromium.so造成的，ingore后就没问题了

**Comment by Everley1993** [comment]
为什么libwebviewchromium.so没办法hook呢？
