### ISSUE TITLE
gnu hash 及 dl_iterate_phdr 疑问

### ISSUE THREAD

**Issue by liudongmiao** [iqiyi/xHook#37]
1. gnu hash 查找方法，似乎与 https://flapenguin.me/2017/05/10/elf-lookup-dt-gnu-hash/ 一致。
与 linker 稍有不同，当然结果肯定是一致的。
linker 版本：https://github.com/aosp-mirror/platform_bionic/blob/master/linker/linker_soinfo.cpp#L183-L250

与此相关的一个疑问是，在 plt 查找过程中，基本上是要遍历两遍的。
一是 gnu hash 没有，要遍历 undef；另外就是直接遍历 plt。
这个过程，个人是觉得没有必须去遍历 undef hash，直接遍历 plt 就好。
目前的实现可能对 elf hash 友好一点。

2. 有计划使用 dl_iterate_phdr 重写么？
毕竟 android 4.X 以下越来越少，而使用 dl_iterate_phdr 的话，可能工作会轻松很多。
自己尝试使用 dl_iterate_phdr 去检查是否被 hook，发现还比较简单。
而在使用 dl_iterate_phdr 的过程中，发现直接部分替代 dlsym，完全可以替代系统隐藏的公开方法。

**Comment by caikelun** [comment]
抱歉，这段时间项目太紧张了，没有及时回复github上的问题。

1. 使用gnu hash时，也会有一部分放在undef中的，如果不遍历undef，有些符号会找不到的。

2. 目前没有这个打算哦，4.x还是有一定量的，比如我厂的app就还没有放弃4.x。另外，还有不少老旧的tv盒子在使用4.x的安卓系统的，tv盒子的换代周期是比较长的。。。

**Comment by liudongmiao** [comment]
好的，谢谢～

**Comment by liudongmiao** [comment]
@caikelun 可能 android q 里，得考虑 dl_iterate_phdr 了。

maps 文件里，根本没有 so 文件信息..但是 dl_iterate_phdr 可以读到。

android q 里也提到了这个改动。

**Comment by caikelun** [comment]
嗯嗯，我目前还没有在Android Q里试过。

> “android q 里也提到了这个改动。”

这个有什么文档或者出处吗？能贴个链接吗？

**Comment by caikelun** [comment]
> 乌龙了，请忽略

好吧。还是感谢你的关注。

**Comment by liudongmiao** [comment]
android q beta 2 出来了，这次应该要挂。当然，自己的库没事。

在 Android P 上，找 `jniRegisterNativeMethods` 时：

```
found jniRegisterNativeMethods(plt+2) in /system/lib64/libandroid_runtime.so, 0x777466e090 -> 0x77749203bc
```

maps 文件为：

```
777445b000-777463f000 r-xp 00000000 fd:00 2194                           /system/lib64/libandroid_runtime.so
7774656000-7774675000 r--p 001f1000 fd:00 2194                           /system/lib64/libandroid_runtime.so
7774675000-7774676000 rw-p 00210000 fd:00 2194                           /system/lib64/libandroid_runtime.so

777491e000-7774924000 r-xp 00000000 fd:00 2113                           /system/lib64/libnativehelper.so
777493d000-777493e000 r--p 0000f000 fd:00 2113                           /system/lib64/libnativehelper.so
777493e000-777493f000 rw-p 00010000 fd:00 2113                           /system/lib64/libnativehelper.so
```

可以看到，`0x777466e090` 在 libandroid_runtime.so 中 r+p 那一行范围内，而值 `0x77749203bc` 也在 libnativehelper.so 中 r+xp 那一行范围内。

而到了 android q beta 2，找 `jniRegisterNativeMethods` 时：

```
found jniRegisterNativeMethods(plt+1) in /system/lib64/libandroid_runtime.so, 0x7db396c740 -> 0x7db15fb014
```
整个 maps 相关文件：

```
7db3787000-7db3844000 r--p 00000000 fd:03 2462                           /system/lib64/libandroid_runtime.so

7db15fe000-7db15ff000 r--p 00006000 07:18 109                            /apex/com.android.runtime/lib64/libnativehelper.so
```

我没有接入 xHook，直接使用的 dl_iterate_phdr。在 android q beta 2 中实际能不能从 `7db3787000-7db3844000` 范围中找到 plt 表，没有实际验证。但是就 dl_iterate_phdr 结果来看，应该是无法找到的。

**Comment by liudongmiao** [comment]
补充说明下，如果是自己的库，没有问题。
dl_iterate_phdr 给出的结果，均在 maps 文件中体现。
