### ISSUE TITLE
是不是 会有一定时间的延时呢

### ISSUE THREAD

**Issue by czgczg308** [iqiyi/xHook#38]
是不是 会有一定时间的延时，我这边  要so加载进去后，然后取得一次值之后 方法 才能被篡改掉

**Comment by caikelun** [comment]
会有延迟的，肯定是目标so先加载，然后再执行hook。你可以试试在java层用asm hook掉System.loadLibrary，执行完System.loadLibrary后立刻xhook_refresh(0)。
