### ISSUE TITLE
搜索rel.plt表第一行会忽略的问题

### ISSUE THREAD

**Issue by dancersky** [iqiyi/xHook#45]
在xh_elf.c文件中xh_elf_hook函数有如下代码：
`xh_elf_plain_reloc_iterator_init(&plain_iter, self->relplt, self->relplt_sz, self->is_use_rela);
		while((NULL != (rel_common = xh_elf_plain_reloc_iterator_next(&plain_iter)))
{
            if(0 != (r = xh_elf_find_and_replace_func(self,
                                                      (self->is_use_rela ? ".rela.plt" : ".rel.plt"), 1,
                                                      symbol, new_func, old_func,
                                                      symidx, rel_common, &found))) return r;
            if(found) break;
        }
`
使用此代码，第一次查找就会从第二行开始，会忽略第一行，如果要hook的函数在rel.plt表中第一行就会hook失败。
可以修改为如下代码，即可正常使用：
`xh_elf_plain_reloc_iterator_init(&plain_iter, self->relplt, self->relplt_sz, self->is_use_rela);
		rel_common = plain_iter.cur;
		while(NULL != rel_common) //(NULL != (rel_common = xh_elf_plain_reloc_iterator_next(&plain_iter)))
        {
            if(0 != (r = xh_elf_find_and_replace_func(self,
                                                      (self->is_use_rela ? ".rela.plt" : ".rel.plt"), 1,
                                                      symbol, new_func, old_func,
                                                      symidx, rel_common, &found))) return r;
            if(found) break;
			rel_common = xh_elf_plain_reloc_iterator_next(&plain_iter);
        }`

**Comment by caikelun** [comment]
修复了：https://github.com/iqiyi/xHook/commit/3f41ae82bc72695208377304b30dc6698621453f
谢谢！

**Comment by dancersky** [comment]
感谢开源，这个项目很有意义！
