### ISSUE TITLE
请教一个问题关于 hook 系统 so 的

### ISSUE THREAD

**Issue by mumaren** [iqiyi/xHook#46]
如果是一个native 程序,直接调用了 libc 的 open 函数,没有经过其他 so.那还可以 hook 这个 open 函数的调用吗 ? 我理解是不可以的,不知是否理解有误?请赐教.

**Comment by caikelun** [comment]
和具体的 so 库，以及 so 库的编译选项，以及 hook 方案都有关系，没法一概而论。
PLT hook 只能 hook PLT 表中的外部函数，一个具体的 so 能 hook 哪些外部调用，用 readelf 看一下才能知道。
如果需要 hook so 内部的调用，可以用 inline hook 方案。
xhook 只支持 PLT hook。

**Comment by mumaren** [comment]
谢谢您的回答. 可能是我没有写清楚,我是想了解这样一个问题.
之前文档写的案例是一个可执行程序,调用 a.so .    a.so 内调用了open 函数,这个open 函数是在 libc 中导出的.  所以可以通过修改 a.so 的表的方式来达到 hook a.so 的 open 调用的目的. 但是如果是可执行程序直接调用了 open 函数,而不是通过 a.so 调用的,那还可以 hook 这次 open 的调用吗?

**Comment by caikelun** [comment]
可以的。可执行文件和动态库都是 ELF 格式的，处理外部调用的方式是一样的。

**Comment by mumaren** [comment]
哦哦 ,那是我理解的有问题,非常感谢.

**Comment by mumaren** [comment]
我试了一下,libc 中的 open 函数是可以 hook,但是 readlink 却不可以,不知道这是为什么
xhook_register(".*\\.so$", "readlink",   (void * )new_readlink, (void **)  &old_readlink) 返回值是正确的.

**Comment by caikelun** [comment]
建议在测试阶段把目标so的名称写全，尽量排除不必要的干扰。

具体问题还是建议你自己调试一下了，也许调试的过程能给你带来更多的知识收益：）

**Comment by mumaren** [comment]
好的,非常感谢您的建议
