### ISSUE TITLE
__LIBC_HIDDEN__函数

### ISSUE THREAD

**Issue by godblesss** [iqiyi/xHook#48]
您好，想请教一下

int android_getnameinfofornet(const struct sockaddr *, socklen_t, char *, size_t, char *, size_t, int, unsigned, unsigned) __LIBC_HIDDEN__;

#define __LIBC_HIDDEN__ __attribute__((visibility("hidden")))
__LIBC_HIDDEN__定义的函数是hook不了的吗？

**Comment by caikelun** [comment]
是的，hidden方法无法使用 PLT hook。
相关内容可以参考大师的文章：https://www.airs.com/blog/archives/307

**Comment by godblesss** [comment]
感谢您的回答
