### ISSUE TITLE
Injecting armeabi-v7a library using x86 injector

### ISSUE THREAD

**Issue by klopez0017** [iqiyi/xHook#50]
Would it be possible to do this?

**Comment by caikelun** [comment]
Sorry. We have no plans to do this.

**Comment by klopez0017** [comment]
Understood, If I may ask only that will it be possible to do so? 

As of the moment I am using an external injector (ChainFire's). The emulator I am using is an x86 platform. So I have to use x86 version of the injector. But the application I wanted to hook up runs over **armeabi-v7a** or **arm64-v8a** so I need to use xhook in **armeabi-v7a** platform. Im doing it via adb..

> adb shell /data/tmp/injector appname /data/tmp/library.so

I just wanna know if its possible. And if you could direct me on how to do it, I would appreciate it.

Thank you so much.

**Comment by caikelun** [comment]
@klopez0017 Yes. This is possible. Refer to: https://github.com/shunix/AndroidGotHook
