### ISSUE TITLE
Do you know how to hook hide a process app in C/C++

### ISSUE THREAD

**Issue by henrytom1703** [iqiyi/xHook#7]

**Comment by caikelun** [comment]
"hide a process app"?   Not sure what you mean......

也可以用中文交流的

**Comment by henrytom1703** [comment]
Hello @caikelun 
Ex. I installed an app which  app ID is "com.app.test". And I want C/C++ to gone this app ID

**Comment by henrytom1703** [comment]
Hell @caikelun .
I also another question.  How to hook Runtime.getRuntime().exec in C/C++?

Thank so much

**Comment by caikelun** [comment]
xhook cannot hook java methods. Try google "android hook java methods"...
